/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.salestracking;

/**
 *
 * @author Monster Huma H5 v4.1
 */
public class BuySellOrder extends javax.swing.JFrame {
    
    /**
     * Creates new form BuySellOrder
     */
    public BuySellOrder() {
        initComponents();
    }
    
    public BuySellOrder(String name) {
        initComponents();
        lbl_name.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_welcome = new javax.swing.JPanel();
        bttn_buy = new javax.swing.JButton();
        bttn_sell = new javax.swing.JButton();
        bttn_myorders = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_welcome.setBackground(new java.awt.Color(204, 255, 204));

        bttn_buy.setText("BUY");
        bttn_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_buyActionPerformed(evt);
            }
        });

        bttn_sell.setText("SELL");
        bttn_sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_sellActionPerformed(evt);
            }
        });

        bttn_myorders.setText("MY ORDERS");
        bttn_myorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_myordersActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Welcome");

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name.setText("a");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Please choose which action you want to take");

        javax.swing.GroupLayout panel_welcomeLayout = new javax.swing.GroupLayout(panel_welcome);
        panel_welcome.setLayout(panel_welcomeLayout);
        panel_welcomeLayout.setHorizontalGroup(
            panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_welcomeLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttn_myorders, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn_sell, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn_buy, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panel_welcomeLayout.setVerticalGroup(
            panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_welcomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl2)
                .addGap(55, 55, 55)
                .addComponent(bttn_buy)
                .addGap(18, 18, 18)
                .addComponent(bttn_sell)
                .addGap(18, 18, 18)
                .addComponent(bttn_myorders)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_buyActionPerformed
        // TODO add your handling code here:
        Buy buy = new Buy(this);
        this.setVisible(false);
        buy.setVisible(true);
    }//GEN-LAST:event_bttn_buyActionPerformed

    private void bttn_myordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_myordersActionPerformed
        // TODO add your handling code here:
        ShowMyOrder myorders = new ShowMyOrder(this);
        this.setVisible(false);
        myorders.setVisible(true);
    }//GEN-LAST:event_bttn_myordersActionPerformed

    private void bttn_sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_sellActionPerformed
        // TODO add your handling code here:
        Sell sell = new Sell(this);
        this.setVisible(false);
        sell.setVisible(true);
    }//GEN-LAST:event_bttn_sellActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_buy;
    private javax.swing.JButton bttn_myorders;
    private javax.swing.JButton bttn_sell;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel panel_welcome;
    // End of variables declaration//GEN-END:variables
}
